name: Juce Change Detector

# Run this action every 5 minutes
on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Runs a single command using the runners shell
    - name: Check for differences
      id: check-diff
      run: |
        cd JUCE
        git pull | grep "Already up to date."
        echo "::set-output name=is-different::$(echo $?)"

    # Runs a set of commands using the runners shell
    - name: Build Projucer
      if: steps.check-diff.outputs.is-different == '1'
      run: |
        echo "Building Projucer..."
