name: Juce Change Detector

# Run this action every 5 minutes
on:
  push:
  schedule:
  - cron: '*/5 * * * *'
  
jobs:
  check-for-changes:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        juce-branch: [master, develop]
        os: [macos-latest, windows-latest]

    steps:
      - name: Test job
      - run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.juce-branch }}