name: Juce Change Detector

# Run this action every 5 minutes
on:
  push:
  schedule:
  - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: true

    # Runs a single command using the runners shell
    - name: Check for differences
      id: check-diff
      run: |
        cd JUCE
        echo "::set-output name=is-different::$(./../scripts/check-for-changes.sh)"
        
    - name: Commit any changes
      if: steps.check-diff.outputs.is-different == 'true'
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Change Checker
        author_email: changechecker@example.com
        message: "CHANGE CHECKER: Updating JUCE submodule"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Runs a set of commands using the runners shell
    - name: Build Projucer
      if: steps.check-diff.outputs.is-different == 'true'
      run: |
        echo ${{ steps.check-diff.outputs.is-different }}
        echo "Building Projucer..."
