name: Juce Change Detector

# Run this action every 5 minutes
on:
  push:
  schedule:
  - cron: '*/5 * * * *'
    
env:
  juce-url:  https://github.com/kieran-rigby-focusrite/JUCE
  
jobs:
  check-for-changes:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        juce-ref: [master, develop]
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        
      - name: Get hash from ref windows
        id: get-hash-windows
        run: |
          cd scripts
          echo "::set-output name=hash::$(get-hash-from-ref.py ${{ env.juce-url }} ${{ matrix.juce-ref }})"

      - name: Testing hash
        run: echo ${{ steps.get-hash.outputs.hash }}
