name: Juce Change Detector

# Run this action every 5 minutes
on:
  push:
  schedule:
  - cron: '*/5 * * * *'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Runs a single command using the runners shell
    - name: Check for differences
      id: check-diff
      run: |
        cd JUCE
        ls
        echo "::set-output name=is-different::$(./../scripts/check-for-changes.sh)"

    # Runs a set of commands using the runners shell
    - name: Build Projucer
      if: steps.check-diff.outputs.is-different == 'true'
      run: |
        echo ${{ steps.check-diff.outputs.is-different }}
        echo "Building Projucer..."
